"""
image_to_asset.py

Convert an image (PNG/JPG) to the RGB565 C++ header format
required by the M5Cardputer UserDemo (Mooncake HAL).

TARGETS:
    Big Icon: 56x56 pixels, RGB565 (16-bit)
    Small Icon: 40x40 pixels, RGB565 (16-bit)

TIP: Set background to #E6E6E6 -- that's what the other apps have.
"""
import sys
import os
try:
    from PIL import Image
except ImportError:
    print("[!] PIL not found. Run: pip install Pillow")
    sys.exit(1)


def generate_header_data(input_path, output_name, size=None):
    """Convert image to a C++ uint16_t RGB565 array string (Big-Endian)"""
    try:
        img = Image.open(input_path)
    except FileNotFoundError:
        print(f"[!] Input image not found: {input_path}")
        return None

    # 1. Clean up and resize
    img = img.convert('RGB')
    if size:
        img = img.resize(size, Image.Resampling.LANCZOS)
        width, height = img.size
    else:
        width, height = img.size
    del size

    total_pixels = width * height

    print(f"[*] Processing {input_path}: {width}x{height} pixels...")

    # 2. Convert pixels to RGB565 hex strings
    hex_values = []
    for y in range(height):
        for x in range(width):
            r, g, b = img.getpixel((x, y))

            # RGB565 Conversion (16-bit total)
            # Standard Big-Endian layout: [RRRRRGGG] [GGGBBBBB]
            # Resulting integer: 0xRRRRRGGGGGGBBBBB
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

            # --- ENDIAN FIX ---
            # Swap the bytes so the display driver reads the components
            # correctly (0x3CE7 becomes 0xE73C)
            swapped = ((rgb565 << 8) & 0xFF00) | ((rgb565 >> 8) & 0x00FF)

            # Format as 0x1234
            hex_values.append(f"0x{swapped:04x}")

    # 3. Format into rows for C++ header readability
    cpp_content = "// Automatically generated by image_to_asset.py\n"
    cpp_content += f"// Input: {os.path.basename(input_path)}\n\n"
    cpp_content += "#include <stdint.h>\n\n"
    cpp_content += (
        f"static const uint16_t image_data_{output_name}[{total_pixels}] "
        f"= {{\n")

    if (width, height) == (240, 135):
        pixels_per_line = 14
    else:
        pixels_per_line = 12
    for i in range(0, total_pixels, pixels_per_line):
        line = "    " + ", ".join(hex_values[i:i + pixels_per_line])
        if i + pixels_per_line < total_pixels:
            line += ",\n"
        else:
            line += "\n"  # final line
        cpp_content += line

    cpp_content += "};\n"
    return cpp_content


def main():
    if len(sys.argv) < 3:
        print(
            "Usage: python image_to_asset.py "
            "<input_image.png> <output.h> [56x56]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    size = None
    if len(sys.argv) == 4:
        size = tuple(int(x) for x in sys.argv[3].split('x'))

    # myapp_big.h 56x56
    # myapp_small.h 40x40
    # fullscreen_logo.h 240x135
    name_without_h = output_file.rsplit('.', 1)[0]
    data = generate_header_data(input_file, name_without_h, size=size)
    if data:
        with open(output_file, "w") as f:
            f.write(data)
        print(f"[OK] Generated {output_file}")


if __name__ == "__main__":
    main()
